name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    
    steps:
    - name: Pull Docker Image
      run: sudo docker pull solomonmarvel97/bportal-auth-service:latest
    - name: Delete Old docker container
      run: sudo docker rm -f bportal-auth-service-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8000 --name bportal-auth-service-container solomonmarvel97/bportal-auth-service
